FROM ubuntu:16.04


RUN apt-get update -y && \
    apt-get install -y python3 python3-dev python3-pip nginx && \
    pip3 install uwsgi && \
    pip3 install nginx

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
COPY ./nginx.conf /etc/nginx/sites-enabled/default

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY . /app

#ENTRYPOINT [ "python3" ]
CMD service nginx start && uwsgi -s /tmp/uwsgi.sock --chmod-socket=666 --manage-script-name --mount /=app:app
